server:
  port: 9090
  servlet:
    context-path: /admin
    session:
      timeout: 3600
      cookie:
        http-only: true
  undertow:
#    accesslog:
#      enabled: true
#      pattern: '%t %a "%r" %s (%D ms)'
    worker-threads: 10
  http2:
    enabled: true
debug: true
trace: false
info:
  java:
    version: @java.version@
  app:
    name: @project.name@
    description: @project.description@
    encoding: @project.build.sourceEncoding@
    version: @project.version@
  contact:
    email: xiongyayun428@163.com
logging:
  level:
    root: DEBUG
    org:
      springframework:
        boot:
          actuate: INFO
          actuate.endpoint.web: INFO
        security: DEBUG
        web: INFO
        beans: INFO
        jdbc: INFO
      hibernate: ERROR
      mybatis: INFO
    com:
      xyy: DEBUG
      alibaba:
        druid: INFO
    de:
      codecentric:
        boot:
          admin: INFO
  file: logs/athena.log
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    log-request-details: true
  messages:
    basename: i18n/messages,i18n/error
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段
    mapper:
      sort-properties-alphabetically: true
  application:
    name: athena-admin
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        instance:
          service-url: http://localhost:${server.port}${server.servlet.context-path}
          # 如果pom.xml中加入spring-boot-starter-security这个包，就需要开启下面的用户密码信息
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
        # 使用HTTP基本身份验证保护SBA服务器api、用户名、密码。
        url: http://localhost:20100
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
  datasource:
    url: jdbc:mysql://localhost:3306/athena?connectTimeout=1000&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: app
    password: ENC(KlPmEBpgGy+0H48b2zbNgw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          # 慢SQL记录
          # merge-sql: true
          # slow-sql-millis: 3000
          log-slow-sql: true
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 10
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: SELECT 'X'
      validation-query-timeout: 3000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: "stat,wall,config"
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
      aop-patterns: com.xyy.athena.user.mapper
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configLocation: classpath:/mybatis-config.xml
  type-aliases-package: tk.mybatis.springboot.model
mapper:
  mappers:
    - tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  pageSizeZero: false
  offsetAsPageNum: false
  rowBoundsWithCount: false
  reasonable: true
  supportMethodsArguments: true
  params: pageNum=pageIndex
#jasypt加密的密匙
jasypt:
  encryptor:
    # 密钥
    password: xiongyayun428