server:
  port: 8761
spring:
  application:
    name: register-master
  security:
    user:
      name: admin
      password: 123456
      roles:
        - user
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"