#server:
#  port: 22222
#  servlet:
##    context-path: /db
#    session:
#      timeout: 3600
#      cookie:
#        http-only: true
#info:
#  app:
#    name: athena-db
#    version: v1.0.0
#  contact:
#    email: xiongyayun428@163.com
#spring:
#  application:
#    name: athena-db
#  security:
#    user:
#      name: admin
#      password: admin
#    basic:
#      # 关掉security框架自带的登陆弹出框
#      enabled: false
#  boot:
#    admin:
#      ui:
#        # 修改网页显示的tab标题
#        title: "雅典娜应用监控管理"
#        # 修改网页的brand的图标和标题
#        brand: "<img src='assets/imgs/icon-spring-boot-admin.svg'><span>雅典娜应用监控管理</span>"
#      client:
#        # 这个URL地址是SBA Server的服务地址，你需要将你的应用注册到该地址上
#        url: http://localhost:20100
#        # 配置连接到监测管理平台的Security安全密码
#        username: ${spring.security.user.name}
#        password: ${spring.security.user.password}
##        instance:
##          metadata:
##            # 配置发送到SBA Server的SBA Client的端点安全密码
##            user.name: ${spring.security.user.name}
##            user.password: ${spring.security.user.password}
#  datasource:
#    url: jdbc:mysql://localhost:3306/athena?connectTimeout=1000&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: app
#    password: app
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filter:
#        stat:
#          log-slow-sql: true
#      # 初始化大小，最小，最大
#      initial-size: 1
#      min-idle: 10
#      max-active: 200
#      # 配置获取连接等待超时的时间
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
#      validation-query: SELECT 'X'
#      validation-query-timeout: 3000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: "stat,wall,config"
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
#      web-stat-filter:
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#        session-stat-enable: false
#        session-stat-max-count: 1000
#      stat-view-servlet:
#        enabled: true
#        url-pattern: "/druid/*"
#        login-username: admin
#        login-password: admin
#      aop-patterns: com.athena.core.mapper
## 官方文档中有提到， SpringBoot 的 Logging 配置的级别有7个：TRACE , DEBUG , INFO , WARN , ERROR , FATAL , OFF
#logging:
#  config:
#    classpath: "log4j2-dev.xml"
#  # 设置日志保存的路径，path和file只需要设置一个，指定path则日志名称固定为spring.log
#  path: ./logs
#  # 打印日志的级别
#  level:
#    root: debug
## 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
##    logfile:
##      external-file: logs/info.log
#  endpoint:
#    health:
#      show-details: ALWAYS
##eureka:
##  instance:
##    hostname: localhost
##    prefer-ip-address: true
##    instance-id: ${spring.cloud.client.ip-address}:${server.port}
##  client:
##    serviceUrl:
##      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
