server:
  port: 20100
  undertow:
    worker-threads: 10
info:
  app:
    name: athena-admin-server
    version: v1.0.0
  contact:
    email: xiongyayun428@163.com
  tags:
    environment: prod
spring:
  application:
    name: athena-admin-server
  output:
    ansi:
      enabled: ALWAYS
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: admin
  mail:
    host: smtp.163.com
    username: xiongyayun428@163.com
    password: ENC(Dk9S4xBvNpdDOYaKMbpTwcvSLYwCtgD8)
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  boot:
    admin:
      ui:
        # 修改网页显示的tab标题
        title: "雅典娜应用监控管理"
#        favicon: static/img/favicon.ico
        # 修改网页的brand的图标和标题
        brand: "<img src='static/img/icon-spring-boot-admin.svg'><span>雅典娜应用监控管理</span>"
#      client:
#        # 这个URL地址是SBA Server的服务地址，你需要将你的应用注册到该地址上
#        url: http://localhost:20100
#        instance:
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
      notify:
        mail:
          from: xiongyayun428@163.com
          to: 531158453@qq.com
          cc: xiongyayun428@163.com
        dingtalk:
          enabled: true
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=5f588ab27b1f7c1f0b2bd82cbe3ee609554141bbf51fad8f133ef2a747945c2f
# 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
#jasypt加密的密匙
jasypt:
  encryptor:
    # 密钥
    password: xiongyayun428