server:
  port: 20100
  undertow:
    worker-threads: 10
info:
  app:
    name: com.xyy.athena.user
    version: v1.0.0
  contact:
    email: xiongyayun428@163.com
spring:
  application:
    name: athena-admin-server
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        # 修改网页显示的tab标题
        title: "雅典娜应用监控管理"
        # 修改网页的brand的图标和标题
        brand: "<img src='assets/imgs/icon-spring-boot-admin.svg'><span>雅典娜应用监控管理</span>"
      client:
        # 这个URL地址是SBA Server的服务地址，你需要将你的应用注册到该地址上
        url: http://localhost:20100
        # 配置连接到监测管理平台的Security安全密码
        username: admin
        password: admin
        instance:
          metadata:
            # 配置发送到SBA Server的SBA Client的端点安全密码
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
# 官方文档中有提到， SpringBoot 的 Logging 配置的级别有7个：TRACE , DEBUG , INFO , WARN , ERROR , FATAL , OFF
logging:
  # 设置日志保存的路径，path和file只需要设置一个，指定path则日志名称固定为spring.log
  path: /java-log
  # 打印日志的级别
  level:
    root: info
# 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      ribbon:
        ConnectTimeout: 1000
        ReadTimeout: 3000
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 100000