server:
  port: 10001
info:
  contact:
    email: xiongyayun428@163.com
eureka:
  instance:
    # eureka控制台显示的Application的名称
    appname: athena-config-server
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:10000/eureka/
spring:
  devtools:
    restart:
      enabled: false
  profiles:
    # 配置服务器使用本地配置，默认git配置
    active: git
  application:
    # 在Eureka中注册的服务名
    name: athena-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xiongyayun428/SpringCloudConfig.git
          search-paths: athena
        native:
          # 配置文件所在位置
          search-locations: classpath:/config
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
          zk-nodes: localhost:2182
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.boot: debug
    org.springframework.cloud: debug

