server:
  port: 9999
  servlet:
    context-path: /
    session:
      timeout: 3600
      cookie:
        name: OAUTH2SESSION
        http-only: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  undertow:
    threads:
      worker: 10
  http2:
    enabled: true
debug: false
trace: false
info:
  java:
    version: ${java.version}
  app:
    name: ${project.name}
    description: ${project.description}
    encoding: ${project.build.sourceEncoding}
    version: ${project.version}
  contact:
    author: Yayun.Xiong
    email: xiongyayun428@163.com
logging:
  level:
    root: INFO
    org:
      springframework:
        boot:
          actuate: INFO
          actuate.endpoint.web: INFO
        security: DEBUG
        web: INFO
        beans: INFO
        jdbc: INFO
      hibernate: ERROR
      mybatis: INFO
    com:
      xiongyayun: DEBUG
      alibaba:
        druid: INFO
        nacos: WARN
    de:
      codecentric:
        boot:
          admin: INFO
  file:
    name: logs/athena.log
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false
spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages,i18n/error
    encoding: UTF-8
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: false
  jackson:
    time-zone: GMT+8
    default-property-inclusion: ALWAYS #如果某一个字段为null，就不再返回这个字段
    mapper:
      sort-properties-alphabetically: true
  application:
    name: athena-auth
  security:
    user:
      name: admin
      password: admin
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
  resources:
    add-mappings: false
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://localhost:${server.port}${server.servlet.context-path}
          # 如果pom.xml中加入spring-boot-starter-security这个包，就需要开启下面的用户密码信息
#          metadata:
#            user:
#              name: ${spring.security.user.name}
#              password: ${spring.security.user.password}
        # 使用HTTP基本身份验证保护SBA服务器api、用户名、密码。
        url: http://localhost:20100
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
  datasource:
    url: jdbc:mysql://47.107.179.245:3306/athena?connectTimeout=1000&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: athena
    password: athena
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          # 慢SQL记录
          # merge-sql: true
          # slow-sql-millis: 3000
          log-slow-sql: true
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 10
      max-active: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: SELECT 'X'
      validation-query-timeout: 3000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: "stat,wall,config"
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: false
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
      aop-patterns: com.xiongyayun.athena.user.mapper
  redis:
    #数据库索引
    database: 0
    host: 47.107.179.245
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

#jasypt加密的密匙
jasypt:
  encryptor:
    # 密钥
    password: xiongyayun428
athena:
  security:
    oauth2:
      storeType: jwt