#server:
#  port: 10100
#  undertow:
#    worker-threads: 10
#info:
#  app:
#    name: athena.user
#    version: v1.0.0
#  contact:
#    email: xiongyayun428@163.com
#spring:
#  devtools:
#    restart:
#      enabled: false
#  security:
#    user:
#      name: admin
#      password: 123456
#  application:
#    name: athena-user