server:
  port: 20100
  undertow:
    worker-threads: 10
info:
  app:
    name: athena-admin-server
    version: v1.0.0
  contact:
    email: xiongyayun428@163.com
  tags:
    environment: prod
spring:
  application:
    name: athena-admin-server
  # 配置SBA Client连接的安全账号密码
  security:
    user:
      name: admin
      password: admin
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
  boot:
    admin:
      ui:
        # 修改网页显示的tab标题
        title: "雅典娜应用监控管理"
#        favicon: static/img/favicon.ico
        # 修改网页的brand的图标和标题
        brand: "<img src='static/img/icon-spring-boot-admin.svg'><span>雅典娜应用监控管理</span>"
      client:
        # 这个URL地址是SBA Server的服务地址，你需要将你的应用注册到该地址上
        url: http://localhost:20100
        instance:
          metadata:
            # 配置发送到SBA Server的SBA Client的端点安全密码
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
#      notify:
#        mail:
#          from: Product@hljinke.com
#          to: xiongyayun@prolinkwm.com
#          cc: minyafeng@prolinkwm.com, shajisheng@hljinke.com
#        dingtalk:
#          enabled: true
#          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=5f588ab27b1f7c1f0b2bd82cbe3ee609554141bbf51fad8f133ef2a747945c2f
    mail:
      host: smtp.exmail.qq.com
      username: Product@hljinke.com
      password: 1qaz@WSX
      protocol: smtp
      default-encoding: UTF-8
      test-connection: false
      properties:
        mail:
          smtp:
            auth: true
# 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS